CREATE TABLE IF NOT EXISTS engine (
    id SERIAL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS car (
    id SERIAL PRIMARY KEY,
    engine_id INT NOT NULL UNIQUE REFERENCES engine(id)
);
CREATE TABLE IF NOT EXISTS driver (
    id SERIAL PRIMARY KEY
);
CREATE TABLE IF NOT EXISTS history_owner (
    id SERIAL PRIMARY KEY,
    driver_id INT NOT NULL REFERENCES driver(id),
    car_id INT NOT NULL REFERENCES car(id)
);